dist: xenial
services:
- postgresql
addons:
  postgresql: "9.4"
branches:
  only:
  - almacenamiento_panel
before_script:
  - cd decide
  - cp local_settings.travis.py local_settings.py
  - psql -U postgres -c "create user decide password 'decide'"
  - psql -U postgres -c "create database decide owner decide"
  - psql -U postgres -c "ALTER USER decide SUPERUSER"
language: python
python:
- '3.6'
install:
  - pip install -r requirements.txt
  - pip install codacy-coverage
  - pip install flake8
script:
  - yes|python manage.py makemigrations --merge
  - yes|python manage.py migrate
  - mkdir decide/migrations
  - touch decide/migrations/__init__.py
  - coverage run --branch --source=. ./manage.py test --keepdb
  - coverage xml
  - python-codacy-coverage -r coverage.xml
  - flake8 . --ignore=E722,E999,E902

notifications:
    email:
      on_success: never
      on_failure: never
deploy:
  on: 
    branch: almacenamiento_panel
  strategy: git
