dist: xenial

services:
  - postgresql
addons:
  postgresql: "9.4"
global:
  - PGPORT=5432
before_script:
  - cp local_settings.travis.py local_settings.py
  - psql -U postgres -c "create user decide password 'decide'"
  - psql -U postgres -c "create database test_decide owner decide"
  - psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
  - "3.6"
env:
- DJANGO=2.0 DB=postgres
before_install:
- cd decide
install:
  - pip install -r requirements.txt
  - pip install codacy-coverage
script:
  - python manage.py test

