dist: xenial

services:
  - mongodb

branches:
  only:
  - almacenamiento_travis
before_script:
  - cd decide
  - cp local_settings.travis.py local_settings.py
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"decide",pwd:"decide",roles:["readWrite"]});'
  
  
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - python ./manage.py makemigrations
  - python ./manage.py migrate
  - python ./manage.py test --keepdb
notifications:
    email:
      on_success: never
      on_failure: never

