# Generated by Django 2.0 on 2020-01-27 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200124_1756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Backup',
        ),
    ]
