# Generated by Django 2.0 on 2020-01-27 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_delete_backup'),
        ('store', '0005_auto_20200110_1013'),
    ]

    operations = [
    ]
